Controllers/OrdersController.cs
using e_organic.Data.Cart;
using e_organic.Data.Services;
using e_organic.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class OrdersController : Controller
    {

        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductService productService,ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {

            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var respose = new ShoppingCartVM
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),

            };
          
            return View(respose);
        }

        public async Task<IActionResult> AddItemToShoppinCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
            
        }


        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> OrderCompleted()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");

        }
    }
}

Controllers/ProductController.cs
using e_organic.Data;
using e_organic.Data.Services;
using e_organic.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        public ProductController(IProductService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {

            var allProducts = await _service.GetAllAsync(n =>n.Vendor);
            return View(allProducts);
        }
        //search method
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync(n => n.Vendor);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allProducts.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
       
            return View("Index", allProducts);
        }
        //Get: movies/detail/1
        public async Task<IActionResult> Details(int id)
        {
            var moviesDetails = await _service.GetProductByIdAsync(id);
            return View(moviesDetails);
        }

        //get:product/create
        public  async Task<IActionResult> Create()
        {
            var dropdownData = await _service.GetProductDropDownValue();
            ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");
            return View();
        }
        //post:product/create/
        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid) {
                var dropdownData = await _service.GetProductDropDownValue();
                ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");

                return View(product);
            }
            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index)) ;
        }

        //get:product/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var moviesDetails = await _service.GetProductByIdAsync(id);
            if (moviesDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = moviesDetails.Id,
                Name = moviesDetails.Name,
                Description = moviesDetails.Description,
                ImageUrl = moviesDetails.ImageUrl,
                Price=moviesDetails.Price,
                ProductCatagory=moviesDetails.ProductCatagory,
                VendorId=moviesDetails.VendorId,
            };
            var dropdownData = await _service.GetProductDropDownValue();
            ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");
            return View(response);
        }
        //post:product/edit/
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {

            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var dropdownData = await _service.GetProductDropDownValue();
                ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");

                return View(product);
            }
            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }



    }
}

Controllers/VendorController.cs
using e_organic.Data;
using e_organic.Data.Services;
using e_organic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class VendorController : Controller
    {

        private readonly IVendorService _service;
        public VendorController(IVendorService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {

            var result = await _service.GetAllAsync();
            return View(result);
        }

        //method to create new vendor
        //get method Vendor/Create
        
        public IActionResult Create()
        {
            return View();
        }
        //post method
        [HttpPost]
        public async Task<IActionResult>Create([Bind("Name,ImageUrl,Description,Address")]Vendor newVendor)
        {
            if (!ModelState.IsValid)
            {
                return View(newVendor);
            }
          await  _service.AddAsync(newVendor);
            return RedirectToAction(nameof(Index));
        }


        //get deatil function
        public async Task<IActionResult>Details(int id)
        {
            var vendorDetails = await _service.GetByIdAsync(id);
            if (vendorDetails == null) return View("NotFound");
            return View(vendorDetails);

        }
        //get edit
        public async Task<IActionResult> Edit(int id)
        {
            var vendorDetails = await _service.GetByIdAsync(id);
            if (vendorDetails == null) return View("NotFound");
            return View(vendorDetails);
        }
        //post method
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Name,ImageUrl,Description,Address")] Vendor vendor)
            {
            if (!ModelState.IsValid) return View(vendor);
                
            await _service.UpdateAsync(id,vendor);
            return RedirectToAction(nameof(Index));
        }

        //get delete
        public async Task<IActionResult> Delete(int id)
        {
            var vendorDetails = await _service.GetByIdAsync(id);
            if (vendorDetails == null) return View("NotFound");
            return View(vendorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfiremd(int id)
        {
            var vendorDetails = await _service.GetByIdAsync(id);
            if (vendorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

           
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info"> You have reached     the end of the internet</h1>
        <hr />
        <a class="btn btn-primary" asp-controller="Product" asp-action="Index">Home Page</a>
    </div>
  
</div>

Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right:25px; bottom:100px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"> </i>Add new
        </a>

    </div>

}

Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;
    
@if (!User.Identity.IsAuthenticated)
{

    <a class="btn btn-outline-success my-2 my--sm-0" asp-controller="Account" asp-action="Login">
        <i class=" bi bi-box-arrow-in-right"></i>Lognin
    </a>
    <span style="padding:5px;"></span>
    <a class="btn btn-outline-primary my-2 my--sm-0" asp-controller="Account" asp-action="Register">
        <i class=" bi bi-person-plus"></i>Register
    </a>
}
else
{
    <span style="padding:5px;"></span>
    @*user profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i>@UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i>Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {

                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i>Users
                    </a>
                </li>
            }

        </ul>

    </div>
    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>Log out
        </button>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e_organic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">e_organic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index"><i class="fas fa-lemon"></i> Products</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>



                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Vendor" asp-action="Index"><i class="bi bi-camera-reels"></i> Vendors</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Product Detail</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> About Us</a>

                                </div>
                            </li>
                        }

                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Product" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a products..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                  <partial name="_Identity.cshtml"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - e_organic
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>