Models/Product.cs
using e_organic.Data;
using e_organic.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Models
{
    public class Product
        :IEntityBase
    {
        [Key]
       public int Id { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Product Image")]
        public string ImageUrl { get; set; }
        [Display(Name = "Price")]
        public double Price { get; set; }
        public ProductCatagory ProductCatagory { get; set; }

        //Relationship 
        //vendor
        public  int VendorId { get; set; }
        [ForeignKey("VendorId")]
        public Vendor Vendor { get; set; }
    }
}

Controllers/OrdersController.cs
using e_organic.Data.Cart;
using e_organic.Data.Services;
using e_organic.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class OrdersController : Controller
    {

        private readonly IProductService _productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IProductService productService,ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productService = productService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {

            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var respose = new ShoppingCartVM
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),

            };
          
            return View(respose);
        }

        public async Task<IActionResult> AddItemToShoppinCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
            
        }


        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productService.GetProductByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> OrderCompleted()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");

        }
    }
}

Controllers/ProductController.cs
using e_organic.Data;
using e_organic.Data.Services;
using e_organic.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        public ProductController(IProductService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {

            var allProducts = await _service.GetAllAsync(n =>n.Vendor);
            return View(allProducts);
        }
        //search method
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync(n => n.Vendor);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allProducts.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
       
            return View("Index", allProducts);
        }
        //Get: movies/detail/1
        public async Task<IActionResult> Details(int id)
        {
            var moviesDetails = await _service.GetProductByIdAsync(id);
            return View(moviesDetails);
        }

        //get:product/create
        public  async Task<IActionResult> Create()
        {
            var dropdownData = await _service.GetProductDropDownValue();
            ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");
            return View();
        }
        //post:product/create/
        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid) {
                var dropdownData = await _service.GetProductDropDownValue();
                ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");

                return View(product);
            }
            await _service.AddNewProductAsync(product);
            return RedirectToAction(nameof(Index)) ;
        }

        //get:product/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var moviesDetails = await _service.GetProductByIdAsync(id);
            if (moviesDetails == null) return View("NotFound");

            var response = new NewProductVM()
            {
                Id = moviesDetails.Id,
                Name = moviesDetails.Name,
                Description = moviesDetails.Description,
                ImageUrl = moviesDetails.ImageUrl,
                Price=moviesDetails.Price,
                ProductCatagory=moviesDetails.ProductCatagory,
                VendorId=moviesDetails.VendorId,
            };
            var dropdownData = await _service.GetProductDropDownValue();
            ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");
            return View(response);
        }
        //post:product/edit/
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductVM product)
        {

            if (id != product.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var dropdownData = await _service.GetProductDropDownValue();
                ViewBag.Vendors = new SelectList(dropdownData.Vendors, "Id", "Name");

                return View(product);
            }
            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }



    }
}

Controllers/ProductsController.cs
using e_organic.Data;
using e_organic.Data.Services;
using e_organic.Data.ViewModels;
using e_organic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsService _service;
            public ProductsController(IProductsService service)
        {
            _service = service;


        }
        public async Task<IActionResult> Index()
        {
            var allProduct = await _service.GetAllAsync(n=>n.Vendor );  
      
            return View(allProduct);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allProduct = await _service.GetAllAsync(n => n.Vendor);

            if (!string.IsNullOrEmpty(searchString)) {
                var filteredResult = allProduct.Where(n => n.name.Contains(searchString) || n.Discription.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allProduct); 
        }
        //GEt:Product/Details/1
        public async Task<IActionResult>Details(int id)
        {

            var ProductDetail = await _service.GetProductByIdAsync(id);
            return View(ProductDetail);
        }

        //cretae/Product
        public async Task<IActionResult> Create()
        {

            var VendorDropdowndata = await _service.GetNewProductDropdownValues();

            ViewBag.Vendors = new SelectList(VendorDropdowndata.Vendors, "id", "name");
            return View();

        }
        //adding product data to the database
        [HttpPost]
        public async Task<IActionResult> Create(NewProductVM product)
        {
            if (!ModelState.IsValid) {

                var VendorDropdowndata = await _service.GetNewProductDropdownValues();


                ViewBag.Vendors = new SelectList(VendorDropdowndata.Vendors, "id", "name");
                return View(product);
            }
            await _service.addNewProductAsync(product);
            return RedirectToAction(nameof(Index));
        }
        //cretae/Product/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var ProductDetails = await _service.GetProductByIdAsync(id);
            if (ProductDetails == null) return View("not found");

            var response = new NewProductVM() {
                id = ProductDetails.id,
                name = ProductDetails.name,
                Discription = ProductDetails.Discription,
                price = ProductDetails.price,
                ProductCategory = ProductDetails.ProductCategory,
                imageUrl = ProductDetails.imageUrl,
                VendorId = ProductDetails.VendorId
            };

            var VendorDropdowndata = await _service.GetNewProductDropdownValues();

            ViewBag.Vendors = new SelectList(VendorDropdowndata.Vendors, "id", "name");
            return View(response);

        }
        //adding product data to the database
        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewProductVM product)
        {
            if (id != product.id) return View("not found");
            if (!ModelState.IsValid) {

                var VendorDropdowndata = await _service.GetNewProductDropdownValues();


                ViewBag.Vendors = new SelectList(VendorDropdowndata.Vendors, "id", "name");
                return View(product);
            }
            await _service.UpdateProductAsync(product);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/VendorsController.cs
using e_organic.Data;
using e_organic.Data.Services;
using e_organic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace e_organic.Controllers
{
    public class VendorsController : Controller
    {
        private readonly IVendorsService _service;
        public VendorsController(IVendorsService service)
        {
            _service = service;

        }
        public async Task<IActionResult> Index()
        {
            var VendorsData = await _service.GetAllAsync();
            return View(VendorsData);
        }

        //Getdata/Vendors/Create

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageUrl,name,Discription")] Vendor vendor)
        {

            if (!ModelState.IsValid) return View(vendor);
            await _service.AddAsync(vendor);
            return RedirectToAction(nameof(Index));
        }

        //Get:Vendors:Detail/1
        public async Task<IActionResult> Details(int id)
        {
            var VendorDetails = await _service.GetByIdAsync(id);
                if (VendorDetails == null) return View("Not Found");
            return View(VendorDetails);

        }
        //Get:Vendor/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var VendorDetails = await _service.GetByIdAsync(id);
            if (VendorDetails == null) return View("Not Found");
            return View(VendorDetails);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("id,ImageUrl,name,Discription")] Vendor vendor)
        {

            if (!ModelState.IsValid) return View(vendor);
            await _service.UpdateAsync(id,vendor);
            return RedirectToAction(nameof(Index));
        }
        //Get:Vendor/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var VendorDetails = await _service.GetByIdAsync(id);
            if (VendorDetails == null) return View("Not Found");
            return View(VendorDetails);

        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var VendorDetails = await _service.GetByIdAsync(id);
            if (VendorDetails == null) return View("Not Found");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Products/Create.cshtml
@using e_organic.Data.ViewModels;
@model NewProductVM

@{
    ViewData["Title"] = "Create a new Vendor";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Vendor</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="name" class="control-label"></label>
                                <input asp-for="name" class="form-control" />
                                <span asp-validation-for="name" class="text-danger"></span>
                            </div>
                            @* <div class="form-group">
                                    <label asp-for="StartDate" class="control-label"></label>
                                    <input asp-for="StartDate" type="date" class="form-control" />
                                    <span asp-validation-for="StartDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EndDate" class="control-label"></label>
                                    <input asp-for="EndDate" type="date" class="form-control" />
                                    <span asp-validation-for="EndDate" class="text-danger"></span>
                                </div>*@
                            <div class="form-group">
                                <label asp-for="price" class="control-label"></label>
                                <input asp-for="price" type="number" class="form-control" />
                                <span asp-validation-for="price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="imageUrl" class="control-label"></label>
                                <input asp-for="imageUrl" class="form-control" />
                                <span asp-validation-for="imageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="VendorId" class="control-label"></label>
                                <select asp-for="VendorId" class="form-control" asp-items="ViewBag.Vendors"></select>
                                <span asp-validation-for="VendorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProductCategory" class="control-label"></label>
                                <select asp-for="ProductCategory" class="form-control" asp-items="Html.GetEnumSelectList<ProductCategory>()"></select>
                                <span asp-validation-for="ProductCategory" class="text-danger"></span>
                            </div>
                            @* <div class="form-group">
                                    <label asp-for="ProducerId" class="control-label"></label>
                                    <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                    <span asp-validation-for="ProducerId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ActorIds" class="control-label"></label>
                                    <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                    <span asp-validation-for="ActorIds" class="text-danger"></span>
                                </div>*@
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Discription" class="control-label"></label>
                                <textarea asp-for="Discription" class="form-control"></textarea>
                                <span asp-validation-for="Discription" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="imageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#imageUrl").on("change", function () {
            var output = document.getElementById("imageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Views/Products/Details.cshtml
 @model Product

@{
    ViewData["Title"] = "Product Details ";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.imageUrl" width="100%" alt="@Model.name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Discription</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Vendors" asp-action="Details" asp-route-id="@Model.VendorId">
                                @Model.Vendor.name
                            </a>
                        </p>
                       @* <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>*@
                        <p class="card-text"><b>Category: </b>@Model.ProductCategory</p>
                       @* <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                    </div>
                                }*@
                          @*  </div>
                        </p>*@

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "List of Product";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.id"><i class="bi bi-pencil-square"></i></a>

                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.imageUrl" width="100%" alt="@item.name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Discription</p>
                            <p class="card-text"><b>Cinema: </b>@item.name</p>
                            <p class="card-text"><b>Category: </b>@item.ProductCategory</p>
                            @*<p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>*@
                         @*   <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>*@

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @item.price.ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Products") 